### ISSUE TITLE
Node 4 offline

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#129]
"This node is offline because Jenkins failed to launch the slave agent on it."

**Comment by gforcada** [comment]
@svx @tisto any ideas why node4 is not reachable by ssh?

**Comment by gforcada** [comment]
@plone/ai-team could you provide any feedback on this? Can we just remove it all together or it will come back at any point?

**Comment by tisto** [comment]
@svx could you reset node4?

**Comment by svx** [comment]
node4 is back online and connected, but someone should really check the setup, there is something with this node and there is something how the jenkins setup is done for this node

**Comment by tisto** [comment]
@svx I know. This is why I asked you to do a full reset of the machine some time ago. :)

I would like to set it up from the scratch.

**Comment by svx** [comment]
Thing is I am kind of swamped with work, maybe I am able to find some time like an hour or so next week, since jenkins is kind of 'special' and usually you guys manage the nodes/master we never included jenkins into our ai.butler setup, so this one is still 'by hand' more or less  :)

So lets write down the steps:

svx:

- rebuild of the bare base, just a base ubuntu 14.04 install
- gives new ip and login to tisto

tisto:

- doing all the jenkins setup 
- in charge of keeping the box up to date

what ports and ips you need open, I am asking for the firewall setup [send me a mail :)]

And also important, do you know why the old setup got buggy ? I would like to avoid that in the future :)

**Comment by tisto** [comment]
I just took node 4 offline before we run into problems. This gives @svx a bit time to reset the machine.

@svx No idea what went wrong. I guess it is much more work to find that out than just to reset the machine.

**Comment by svx** [comment]
Like I said above there is not really a reset, that does means a new base install :)

**Comment by tisto** [comment]
Crap. I wasn't aware that this is a new base install. Though, I still think finding the problem would be much much more work...

**Comment by svx** [comment]
Yes the reasons fro that a above :)  so we go with:

svx:

    rebuild of the bare base, just a base ubuntu 14.04 install
    gives new ip and login to tisto

tisto:

    doing all the jenkins setup
    in charge of keeping the box up to date

?

what ports and ips you need open, I am asking for the firewall setup [send me a mail :)]

**Comment by gforcada** [comment]
@svx with ssh and http(s) I think it's enough, as jenkins master connects to them via ssh

**Comment by svx** [comment]
meaning $IP of master and ssh should be enough ?

**Comment by gforcada** [comment]
$IP of the node :-)

**Comment by svx** [comment]
you want to allow a connection from/to master right ? so the $IP of master should be allowed to connect [incoming], of course you have to allow $IP of node at master

**Comment by gforcada** [comment]
Oh I see, yes of course, but also from anywhere in the world (i.e. we also want to connect via ssh to the node)

**Comment by svx** [comment]
yes !

**Comment by gforcada** [comment]
Up again!!

**Comment by mauritsvanrees** [comment]
Thanks all!
