### ISSUE TITLE
PR testing reporting broken

### ISSUE THREAD

**Issue by jensens** [plone/jenkins.plone.org#140]
looks like the status report back to github on jenkins for PR tests is broken, on github tests stick to pending.

**Comment by gforcada** [comment]
The problem is that jenkins builder scripts (where we put the bootstrap && bin/buildout && bin/test ) stop automatically as soon as there is an error. So if you have something like:

```
bin/this-will-fail
bin/something-else
```

The ``bin/something-else`` will not be executed, and thus the script to update github pull requests does not run.

I will try to see if you can actually go around it.

**Comment by gforcada** [comment]
Testing a possible solution on http://jenkins.plone.org/job/pull-request-5.0/703/console (PR https://github.com/plone/buildout.coredev/pull/157)

**Comment by gforcada** [comment]
Works :-)

**Comment by jensens** [comment]
thanks a lot?!

**Comment by jensens** [comment]
-?
