### ISSUE TITLE
npm installation is broken

### ISSUE THREAD

**Issue by gforcada** [plone/jenkins.plone.org#143]
Trying to bring node4 back online is giving me errors when installing node.

For whichever reason I did a manual installation of it, should we just switch to the already provided by Ubuntu packaged versions?

**Comment by tisto** [comment]
I can look into this. I will set up a Jenkins instance from the scratch for a client and I was planing to look into node/nvm for this anyways. 

We do not use the Ubuntu package because it is always outdated. This is Javascript, the only working version is always the latest one. Everything else is broken and nobody cares. ;)

**Comment by gforcada** [comment]
Ok, thanks for looking into it. But right now we are the ones outdated. We are downloading a specific version of npm not the latest one :-)

**Comment by tisto** [comment]
I know. We can't just always download the latest version. This would mean we would have to pre-check our setup with every Ansible run (because it could break our build). We have to manually update the version to be sure it is safe. Feel free to upgrade and test...

**Comment by gforcada** [comment]
This is already solved.
