### ISSUE TITLE
Disable changelog verifier fore buildout.coredev

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/jenkins.plone.org#172]
In buildout.coredev we have no `CHANGES.rst` file, so the verifier complains that there is no changelog entry. See for example https://github.com/plone/buildout.coredev/pull/213
Maybe add a list of packages that are ignored by this check? The coredev buildout is the most important one that comes to mind.

**Comment by gforcada** [comment]
Yeah, I had that in mind already and some packages were already there, so it was as simple as adding another element on a list :-)

Fixed in https://github.com/plone/mr.roboto/commit/18ea4d22a68739ad5e2ff86191b33a8ca283bc72 and deployed. As soon as you change the pull request it will not be shown anymore.

Thanks for reporting!

**Comment by mauritsvanrees** [comment]
Yep, that works. Thanks.
