### ISSUE TITLE
Job to handle dist.plone.org uploads

### ISSUE THREAD

**Issue by esteele** [plone/jenkins.plone.org#175]
The dist.plone.org upload part of the release process is a bit time consuming and could be replaced with a fairly simple jenkins job. 

My process is basically to run buildout against a config with

```
[buildout]
extends = core.cfg

eggs-directory = release-cache/eggs
download-cache = release-cache/downloads
extends-cache = release-cache/extends

auto-checkout =
```

and then upload the versions.cfg and everything in release-cache/downloads/dist/ to a <whateverversion-pending> directory on dist.plone.org.

**Comment by gforcada** [comment]
@esteele some questions then:

- credentials for dist.plone.org
- which folder on dist.plone.org I guess is not always the same, so how does the script knows where to upload it?
- by versions.cfg you mean buildout.coredev's versions.cfg right?

Once the credentials is sorted out it seems fairly trivial. I will give it a try today or tomorrow.

**Comment by svx** [comment]
Hold on please and wait a minute ! :)

I like the idea, but IMHO it is not smart to rush things now !

First of all I have some security concerns which we have to iron out :)

- This would mean we would have to create a restricted user, which can only upload without login to dist, no passwd, key only

- I am further a bit worried because our jenkins setup is not *that* secure, so that also would mean:
* harden the server [jenkins] setup/conf [login,firewall,key,ports, fail2ban tweaks,...]
* keep them up to date [server]

There is also still the open task to move dist to a new/other machine, since it is only files, the [my] idea was to host all these on the same server were we host the old svn [archive.plone.org].

I am not against it at all, but like I said I would like to review/change/fix some things first :)

**Comment by gforcada** [comment]
@svx let's do it then, because I'm half done already :-)

Actually we could keep the job as it is now, only fetch everything, but no uploading, and one then has to log in into the server and do the scp manually, so no stored credentials are needed...

The job: http://jenkins.plone.org/view/Release/job/release-upload-to-dist/ 

@esteele can you double-check that what's on the environment is ok: http://jenkins.plone.org/view/Release/job/release-upload-to-dist/ws/

**Comment by svx** [comment]
@gforcada if we saying for now someone is uploading manually everything is cool, if we really want that done by jenkins, now, I would like to talk about that first in a private conversation :)

**Comment by gforcada** [comment]
@svx ok let's discuss by mail then

**Comment by gforcada** [comment]
Reference as well: https://github.com/plone/jenkins.plone.org/issues/101

**Comment by gforcada** [comment]
@svx would it be a solution if we host dist.plone.org on jenkins.plone.org itself? This way it can be an internal copy of files, without any network restriction needs. With cloudflare on top it can be probably not so network hungry?

**Comment by mauritsvanrees** [comment]
FWIW, how I do it now, is with [`release/tox.ini`](https://github.com/plone/buildout.coredev/blob/5.2.10/release/tox.ini#L35-L55) which uses pip to get all distributions, both a pip on Python 2.7 and 3.7 to get most of them. Then I do an scp or rsync to dist.plone.org.

I only do this on 5.2 because we are used to it and I don't want to break expectations. I do not do this on 6.0: it is far less common these days that people delete distributions from PyPI, which was the main reason for package uploads I think.

Oh, for 6.0 I still scp the other files, like `versions.cfg` and `constraints.txt`. No plans on changing that.
