### ISSUE TITLE
plone.themetest is being used?

### ISSUE THREAD

**Issue by gforcada** [plone/jenkins.plone.org#219]
@datakurre @tisto as you are the ones getting the failure for these jobs...

For years we have had a version specific jenkins job for https://github.com/plone/plone.themepreview but actually is always building 5.x-latest.

So the question is two fold:
- do we want to build for each major Plone version? (that would be 4.3.x, 5.1.x and 5.2.x, I guess 5.0 is already old news)
- are these screenshots being used at all? Should we remove it all together?

**Comment by datakurre** [comment]
I’m sorry for not managing to fix these tests.

I did look them last time in January. Back then there was some error with the commands (like it run all the job script commands on single line and failing because of that), and again I was unable to repoduce it because of some new issue with vagrant setup. (It was weekend, so I did not want to bother anyone and then this fell under radar again.)

Let’s remove these now and create them again if someone request them. Right now they have been broken so long that they are not used. And testing theming pastanaga would probably need new approach anyways.

Thanks Gil for your time on these and sorry :(

**Comment by gforcada** [comment]
No need to apologize at all! I broke them when I migrated all jobs to use virtualenvs.

I fixed them yesterday, and at least these ones are back in track.

If there is interest we can keep them, of course, that's not a problem.

The question is if someone needs them.

**Comment by datakurre** [comment]
They were created originally at Cathedral sprint to give visual feedback of Barceloneta theme development (and possible regression) on different viewports. I don’t believe they are actively used anymore. There is very little development on Barceloneta and this just takes screenshots, not really test for regression.

We could make something better when someone has need for these again. Eg. knitting visual regression test based on OpenCV for robot tests was easier than I expected.
