### ISSUE TITLE
Low number of Nodes?

### ISSUE THREAD

**Issue by jensens** [plone/jenkins.plone.org#256]
I found Jenkins runs on one node only at the moment. 

Also the BlueDynamics Alliance provided node (tau) seems not to be connected (server Idles all the time). If there is anything I can do to help please ping me.

**Comment by gforcada** [comment]
Node5 and Node7 were the servers provided by the Foundation that were rented since October/November for sprints/conference and they are over now (get a sprint and ask for budget again :+1: )

Node4 is the one you generously provided. Some weeks/month ago was behaving weirdly, lots of errors and was significantly slow, so I took it out, or it was disconnecting itself, can't remember exactly now.

I can revisit it and bring it up.

**Comment by gforcada** [comment]
It is up and running, if any of you spot that it behaves weirdly, report it and we can disable it again. Hopefully not :smile:

**Comment by jensens** [comment]
Hmm, this is local SSD storage and it should just work. Please ping me if it is behaving weird again.
