### ISSUE TITLE
Delete python 2.7 jobs?

### ISSUE THREAD

**Issue by gforcada** [plone/jenkins.plone.org#350]
On the [release schedule](https://plone.org/download/release-schedule) it says that Plone 5.2 is only supported for Python 3.8 until late this year (2024), but that Python 2.7 is only meant to be used as a stepping stone to move to Python 3.8.

Given that, do we want to keep the Jenkins jobs for Python 2.7 for Plone 5.2? Or can we remove them already? 🤔 Or a middle ground: move them to a `Core Schedule`, i.e. run them once a week.

**Comment by mauritsvanrees** [comment]
No, please keep testing on 2.7.  It is easy for something to break here unnoticed if someone commits a PR and only tests it on Python 3.
There is not much happening on 5.2 anymore, so the tests probably already run less than once a week.
If it helps, we could restrict the 2.7 jobs to be run only on for example Node 1, so that other Nodes do not need Python 2 anymore.  But I suspect this would make the setup actually harder.
BTW, I probably want to do one last 5.2 release this spring, even though it is technically out of maintenance.
