### ISSUE TITLE
add branch to allcommits messages

### ISSUE THREAD

**Issue by davisagli** [plone/jenkins.plone.org#83]
I saw the new allcommits messages coming in:

![screen shot 2015-02-27 at 9 34 34 am](https://cloud.githubusercontent.com/assets/49014/6417685/0cc7dbb0-be64-11e4-9aeb-8c1f58916c8d.png)

Could we add the branch name to the message?

What does fc stand for?

**Comment by tisto** [comment]
fc stands for fake commit. @bloodbare needs a way to detect those kind of requests. I already recommended to use [<package name>] <original commit message>.

Ideally I would like to have something like "[4.3][plone.app.discussion] This is a commit message."

@bloodbare said the commit message can become quite long and that is a problem. we postponed the discussion because we did not want to delay the final migration.

**Comment by gforcada** [comment]
Why not just keep it like:

[plone.app.discussion][master]

And the commit message and everything else on the commit message body rather than on the first line

@tisto the buildout.coredev branch in your example wouldn't be redundant? you already made a commit on that branch, so you already *know* is on that branch...

**Comment by tisto** [comment]
@gforcada mr.roboto needs to be able to identify those fake commits. I think that the original commit message (even truncated) would be more important, e.g. "[fc][plone.app.discussion] Fix typo."

I would somehow like to change "fc" to something else. People don't know what that means, maybe "pkg". I would guess everybody would at least know that this means package and it does not have this negative "fake" connotation.

**Comment by davisagli** [comment]
Maybe "auto" or "robot". Most of the commits made by humans are package changes too.

David Glick
(mobile)

**Comment by bloodbare** [comment]
Does not make sense to write the plone version as its intrinsic in the
coredev branch, as its a push, not a commit i may have tons of commits on
it, so on message i send all them and as header the package name and
branch. We can change to show the commit message but then I would need to
commit on coredev a commit for each subcommit of the push.

I can change from [fc] to [robot]
El dg, 1 març, 2015 a les 18:47 David Glick <notifications@github.com> va
escriure:

**Comment by gforcada** [comment]
What about ``[ci]`` for the sake of options :)

**Comment by tisto** [comment]
I would prefer something [pkg], because [ci] or [robot] just refer to the system that automatically creates those commits. Though, [ci] and [robot] could do buildout.coredev commits as well (this depends on our internal structure). [pkg] is only true for those package commits, since buildout.coredev itself is no [pkg]. 

Maybe we should ask people that are not involved with the internals about their opinion...

**Comment by gforcada** [comment]
Let's make a poll? (just kidding)

**Comment by gforcada** [comment]
The branch is already there, not in the first line of the commit message though.
