### ISSUE TITLE
Allow plip implementers to provide an email address that is used for notifications.

### ISSUE THREAD

**Issue by tisto** [plone/jenkins.plone.org#87]
First, we could add the email addresses fo the PLIP implementer to jobs.yml. Later we could read them from the plip cfg so people can add/remove ppl themself.

**Comment by gforcada** [comment]
Sounds like a good idea, something like this?

```
[buildout]
extends = plipbase.cfg
email = my@email.org
```

I see that for example https://github.com/plone/buildout.coredev/blob/5.0/plips/plip10359-security-controlpanel.cfg has some comments at the top describing the PLIP itself, maybe we can just use that also?

```
# PLIP: https://dev.plone.org/ticket/10359
# github: https://github.com/plone/Products.CMFPlone/issues/216
# email: my@email.org
# description:
# Convert security control panel to use z3c.form
# Use registry configuration
# Move it to Products.CMFPlone
```

So that it's a bit easier to parse, and actually, if we get around to improve mr.roboto/jenkins we could ping back the build status on the github issue...

**Comment by tisto** [comment]
@gforcada sounds good! A descriptive header should be a requirement anyways.

**Comment by gforcada** [comment]
Should we instead use the email of the one that runs the jenkins job just like the pull requests? It will make more sense IMHO.

I could create the PLIP cfg and add myself as the one to notify, but someone else could be the one working on it later on and it will still be me getting the notifications...

**Comment by gforcada** [comment]
I created a pull request for it: https://github.com/plone/jenkins.plone.org/pull/98
